### ISSUE TITLE
Querying by virtual attribute

### ISSUE THREAD

**Issue by joewoodhouse** [overlookmotel/sequelize-virtual-fields#7]
Hiya,

This might be a stupid question, but I'm assuming it's not possible to query by a virtual attribute e.g. in a "where"?

For example:

```
MyModel.find({
  where:{
    virtualAttribute: 'bob
  }
}).then(....)
```

If not, would it be a massive technical challenge to add this in? I'm happy to have a go at making a PR myself, but be good to know what the general feeling was!

**Comment by overlookmotel** [comment]
Hi @joewoodhouse.

Sorry for the _very_ long delay in replying.

I'm afraid that this isn't going to be possible. The where clause is executed directly on the database in SQL. Since the getters for virtual fields (which is what would define what the `where` clause should be) are written in Javascript, there's no practical way to translate it into SQL.

Well, OK, I suppose there could be an extension to the API which would allow the user to define a function that translates a virtual where clause into a "real" where clause. `sequelize-virtual-fields` would then have to parse all `where` options, find where they refer to virtual fields and then call the user-defined translation function. But:
1. These where-parsing functions written by the user would have to be very complex to take into account all the variations of the `where` option (e.g. `where: {$ne: value}`, `where: {$gt: value}`)
2. The internal `sequelize-virtual-fields` code would also be pretty complex

I think the use case is slim so I don't think it's worth the effort. But if you feel strongly about this and want to do the work yourself, let's discuss further.

I'm going to close this issue now as I don't think it's going to happen. But feel free to re-open if you're willing to take this on and work up a PR. But please don't just submit a PR - let's discuss the API first.
